// <auto-generated />
using System;
using Kickify.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kickify.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231085415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kickify.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeIconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriteriaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CriteriaValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnnouncementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ShowFrom")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ShowTo")
                        .HasColumnType("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ShowFrom");

                    b.ToTable("Announcements", "system");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Confirmed");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VenueAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingDate");

                    b.HasIndex("FieldId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Bookings", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("ChatMessages", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasComment("NULL = root comment, NOT NULL = reply");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalReplies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Only count for root comments");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CommentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.CommentLike", b =>
                {
                    b.Property<Guid>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LikeId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentLikes", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.EloConfiguration", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KBase")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Base K factor");

                    b.Property<decimal>("KFeedback")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KPerformance")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KRole")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KSentiment")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KTrust")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KWinloss")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ConfigId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("EffectiveFrom");

                    b.HasIndex("IsActive");

                    b.ToTable("EloConfigurations", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.EloHistory", b =>
                {
                    b.Property<Guid>("EloHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationDetails")
                        .HasColumnType("text")
                        .HasComment("JSON with all coefficients");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EloAfter")
                        .HasColumnType("integer");

                    b.Property<int>("EloBefore")
                        .HasColumnType("integer");

                    b.Property<int>("EloChange")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FeedbackComponent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PerformanceComponent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("RoleComponent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("SentimentComponent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("TrustComponent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WinLossComponent")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("EloHistoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("EloHistories", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PeakHourSurcharge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Grass, Artificial, etc.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("FieldId");

                    b.HasIndex("VenueId");

                    b.ToTable("Fields", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttackRating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("CommunicationRating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefenseRating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.Property<int>("FairplayRating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevieweeResponse")
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SentimentLabel")
                        .HasColumnType("text");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("AI-analyzed: -1.00 to 1.00");

                    b.Property<int>("TeamworkRating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.HasKey("FeedbackId");

                    b.HasIndex("MatchId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("MatchId", "ReviewerId", "RevieweeId")
                        .IsUnique();

                    b.ToTable("MatchFeedbacks", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchPreset", b =>
                {
                    b.Property<Guid>("PresetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomLocation")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PresetId");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchPresets", "match");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchRoom", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomLocation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DepositPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<int>("FilledSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("date");

                    b.Property<string>("MatchFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResultConfirmedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("count of confirmations");

                    b.Property<string>("Rules")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open");

                    b.Property<int?>("TeamAScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamBScore")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDepositCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Public");

                    b.HasKey("RoomId");

                    b.HasIndex("FieldId");

                    b.HasIndex("HostId");

                    b.HasIndex("MatchDate");

                    b.HasIndex("Status");

                    b.ToTable("MatchRooms", "match");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "identity");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ChatMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MatchInvites")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("MatchResults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("RoomUpdates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("SystemAnnouncements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences", "identity");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerAchievement", b =>
                {
                    b.Property<Guid>("PlayerAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PlayerAchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("PlayerAchievements", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AfkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentElo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxWinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MvpCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PreferredPositions")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("JSON array: [\"ST\", \"CM\", \"CB\"]");

                    b.Property<int>("ReportCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalMatches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TrustScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(100.00m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles", "identity");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceUrls")
                        .HasColumnType("text")
                        .HasComment("JSON array of screenshot URLs");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReportId");

                    b.HasIndex("MatchId");

                    b.HasIndex("ReportedId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("Status");

                    b.ToTable("PlayerReports", "evaluation");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("TotalComments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Public");

                    b.HasKey("PostId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PostLike", b =>
                {
                    b.Property<Guid>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LikeId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostLikes", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PostMedia", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasComment("For videos (seconds)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasComment("In bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasComment("For images/videos");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("For videos");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasComment("For images/videos");

                    b.HasKey("MediaId");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedia", "social");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.RoomInvitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.HasKey("InvitationId");

                    b.HasIndex("InviteeId");

                    b.HasIndex("InviterId");

                    b.HasIndex("RoomId", "InviteeId")
                        .IsUnique();

                    b.ToTable("RoomInvitations", "match");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.RoomParticipant", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp");

                    b.Property<bool>("CheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("DepositPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Position")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("ST, CM, CB, etc.");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamAssignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ParticipantId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique();

                    b.ToTable("RoomParticipants", "match");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("RequestDetails")
                        .HasColumnType("text")
                        .HasComment("JSON");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs", "system");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("Amenities")
                        .HasColumnType("text")
                        .HasComment("JSON: parking, shower, etc.");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("VenueId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Venues", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueOperatingHour", b =>
                {
                    b.Property<Guid>("HoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("HoursId");

                    b.HasIndex("VenueId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("VenueOperatingHours", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenuePhoto", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("PhotoId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenuePhotos", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerResponse")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasComment("1-5");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId");

                    b.HasIndex("VenueId");

                    b.HasIndex("UserId", "BookingId")
                        .IsUnique();

                    b.ToTable("VenueReviews", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueWallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBankVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("WalletId");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("VenueWallets", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasComment("booking_id or withdrawal_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Withdrawal", b =>
                {
                    b.Property<Guid>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("WithdrawalId");

                    b.HasIndex("WalletId");

                    b.ToTable("Withdrawals", "venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "Creator")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Field", "Field")
                        .WithMany("Bookings")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "MatchRoom")
                        .WithOne("Booking")
                        .HasForeignKey("Kickify.Domain.Entities.Booking", "RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("MatchRoom");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "MatchRoom")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kickify.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.CommentLike", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.EloConfiguration", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "Creator")
                        .WithMany("EloConfigurations")
                        .HasForeignKey("CreatorUserId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.EloHistory", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "Match")
                        .WithMany("EloHistories")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("EloHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Field", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Venue", "Venue")
                        .WithMany("Fields")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchFeedback", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "Match")
                        .WithMany("MatchFeedbacks")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Reviewee")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Reviewer")
                        .WithMany("GivenFeedbacks")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchPreset", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Field", "Field")
                        .WithMany("MatchPresets")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("MatchPresets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchRoom", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Field", "Field")
                        .WithMany("MatchRooms")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kickify.Domain.Entities.User", "Host")
                        .WithMany("HostedRooms")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("Kickify.Domain.Entities.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerAchievement", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Achievement", "Achievement")
                        .WithMany("PlayerAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("PlayerAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("Kickify.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PlayerReport", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "Match")
                        .WithMany("PlayerReports")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kickify.Domain.Entities.User", "Reported")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Reporter")
                        .WithMany("ReportsMade")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Resolver")
                        .WithMany("ReportsResolved")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Match");

                    b.Navigation("Reported");

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Post", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Post", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.RoomInvitation", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "Invitee")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "Inviter")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "MatchRoom")
                        .WithMany("RoomInvitations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("MatchRoom");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.RoomParticipant", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.MatchRoom", "MatchRoom")
                        .WithMany("RoomParticipants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("RoomParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.SystemLog", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("SystemLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Venue", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.User", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueOperatingHour", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Venue", "Venue")
                        .WithMany("VenueOperatingHours")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenuePhoto", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Venue", "Venue")
                        .WithMany("VenuePhotos")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueReview", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Booking", "Booking")
                        .WithMany("VenueReviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.User", "User")
                        .WithMany("VenueReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickify.Domain.Entities.Venue", "Venue")
                        .WithMany("VenueReviews")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueWallet", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.Venue", "Venue")
                        .WithOne("VenueWallet")
                        .HasForeignKey("Kickify.Domain.Entities.VenueWallet", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.VenueWallet", "VenueWallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueWallet");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Withdrawal", b =>
                {
                    b.HasOne("Kickify.Domain.Entities.VenueWallet", "VenueWallet")
                        .WithMany("Withdrawals")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueWallet");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("PlayerAchievements");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Booking", b =>
                {
                    b.Navigation("VenueReviews");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Field", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MatchPresets");

                    b.Navigation("MatchRooms");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.MatchRoom", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("ChatMessages");

                    b.Navigation("EloHistories");

                    b.Navigation("MatchFeedbacks");

                    b.Navigation("PlayerReports");

                    b.Navigation("RoomInvitations");

                    b.Navigation("RoomParticipants");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ChatMessages");

                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("EloConfigurations");

                    b.Navigation("EloHistories");

                    b.Navigation("GivenFeedbacks");

                    b.Navigation("HostedRooms");

                    b.Navigation("MatchPresets");

                    b.Navigation("NotificationPreference");

                    b.Navigation("Notifications");

                    b.Navigation("PlayerAchievements");

                    b.Navigation("PlayerProfile");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("ReportsMade");

                    b.Navigation("ReportsReceived");

                    b.Navigation("ReportsResolved");

                    b.Navigation("RoomParticipations");

                    b.Navigation("SentInvitations");

                    b.Navigation("SystemLogs");

                    b.Navigation("VenueReviews");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("VenueOperatingHours");

                    b.Navigation("VenuePhotos");

                    b.Navigation("VenueReviews");

                    b.Navigation("VenueWallet");
                });

            modelBuilder.Entity("Kickify.Domain.Entities.VenueWallet", b =>
                {
                    b.Navigation("WalletTransactions");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
